### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by SmileyHappy** [dslul/openboard#175]
Hello developer , I follow project
One issue when choose multi language
Please help me. Thank you so much.

 android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)
        at com.android.inputmethod.latin.utils.SubtypeLocaleUtils$1.job(SubtypeLocaleUtils.java:1)
        at com.android.inputmethod.latin.utils.SubtypeLocaleUtils$1.job(SubtypeLocaleUtils.java:1)
        at com.android.inputmethod.latin.utils.RunInLocale.runInLocale(RunInLocale.java:40)

**Comment by jnnkB** [comment]
Hey, what do you mean by "when choose multi language"? Did you try to enable multiple languages and then the app crashed? Is this problem still occurring in the latest release?

**Comment by William150722** [comment]
Hi @jnnkB able to find out the issues?
<img width="1064" alt="Screenshot 2022-08-24 at 4 18 45 PM" src="https://user-images.githubusercontent.com/111726325/186368113-f05bb26b-1862-4847-9727-947071c88560.png">

**Comment by William150722** [comment]
@SmileyHappy @jnnkB any idea to solve it? Thanks.

**Comment by jnnkB** [comment]
@William150722 Could you maybe describe what you did that led to this crash? This would make investigation easier for the developers of this keyboard :)

**Comment by William150722** [comment]
Hi @jnnkB I would like to describe but it no going to happen in my local project, but it always occur in play console log
