### ISSUE TITLE
App crash when opening keyboard

### ISSUE THREAD

**Issue by EbonJaeger** [dslul/openboard#34]
Since updating to 1.3, OpenBoard fails to open when selecting any text input area, and the phone says it has stopped. This is on an LG V64VL (Fiesta) running Android 7.0. I'd love to debug this further, but I have no idea how to get any kind of log or stacktrace from a phone.

*EDIT: I finally figured out how to get crash and bug stuff from remote debugging. Hopefully this is it:
```
--------- beginning of crash
01-27 09:23:42.232  3873  3873 E AndroidRuntime: FATAL EXCEPTION: main
01-27 09:23:42.232  3873  3873 E AndroidRuntime: Process: org.dslul.openboard.inputmethod.latin, PID: 3873
01-27 09:23:42.232  3873  3873 E AndroidRuntime: kotlin.KotlinNullPointerException
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.accessibility.KeyboardAccessibilityDelegate.setKeyboard(KeyboardAccessibilityDelegate.kt:53)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.accessibility.MainKeyboardAccessibilityDelegate.setKeyboard(MainKeyboardAccessibilityDelegate.kt:57)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.MainKeyboardView.setKeyboard(MainKeyboardView.java:405)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.KeyboardSwitcher.setKeyboard(KeyboardSwitcher.java:152)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.KeyboardSwitcher.setAlphabetKeyboard(KeyboardSwitcher.java:211)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.internal.KeyboardState.setAlphabetKeyboard(KeyboardState.java:305)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.internal.KeyboardState.onLoadKeyboard(KeyboardState.java:143)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.keyboard.KeyboardSwitcher.loadKeyboard(KeyboardSwitcher.java:123)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.latin.LatinIME.onStartInputViewInternal(LatinIME.java:990)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.latin.LatinIME$UIHandler.onStartInputView(LatinIME.java:507)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at org.dslul.openboard.inputmethod.latin.LatinIME.onStartInputView(LatinIME.java:812)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.showWindowInner(InputMethodService.java:1645)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1596)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:446)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:206)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6314)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
01-27 09:23:42.232  3873  3873 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by dslul** [comment]
@EbonJaeger I'm sorry for this, I received some emails, I can't reproduce these crashes on my phones, I'll upload v1.2 again (play console doesn't allow to revert an update). This was embarrassing.

**Comment by EbonJaeger** [comment]
Hey no worries, that's just the way it goes sometimes! I am using English (US) on my keyboard. Let me know if you need anything more!

**Comment by Tobiplayer3** [comment]
It also crashes on my LG G7 (Android 9) using the German layout.

**Comment by dslul** [comment]
can someone test [this apk](https://github.com/dslul/openboard/releases/download/v1.3/openboard-1.3.apk) and tell me if it still happens? Thank you

**Comment by Tobiplayer3** [comment]
Works perfectly!

**Comment by EbonJaeger** [comment]
I can't seem to install this manually, so I guess I'm just waiting for it to reach me on Google Play.

**Comment by Tobiplayer3** [comment]
@EbonJaeger You have to remove the Google Play version first, then you can install the apk.

**Comment by EbonJaeger** [comment]
@Tobiplayer3 will that nuke my settings?

**Comment by dslul** [comment]
@EbonJaeger the update should be already live on the playstore (yes deleting the app deletes also its settings)

**Comment by EbonJaeger** [comment]
@dslul yeah, it just got to me. Fix'd!
